name: Add Test Results Label to PR

on:
  workflow_run:
    workflows: ["UI Tests on Windows and MacOS 🧪"]
    types:
      - completed

jobs:
  remove-label:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Remove Failed Tests Label
        uses: buildsville/add-remove-label@v2.0.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          labels: Failed Automation Test
          type: remove

  add-label:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Add Failed Tests Label
        uses: christianvuerings/add-labels@v1
        with:
          labels: |
            Failed Automation Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
