name: UI Automated Tests on Windows 🧪

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout testing directory 🔖
        uses: actions/checkout@v3
        with:
          repository: Satellite-im/Uplink

      - name: Set up cargo cache 🛠️
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13

      - name: Use cmake
        run: cmake --version

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{env.GITHUB_TOKEN}}

      - name: Build resources
        run: cargo build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Uplink-Windows
          path: |
            target/release/uplink.exe

      - name: Compress Windows Build
        shell: powershell
        run: |
          Compress-Archive target/debug/uplink.exe target/debug/Uplink-Win.zip

      - name: Copy file to release
        uses: softprops/action-gh-release@v1
        with:
          files: target/debug/Uplink-Win.zip
