name: UI Automated Tests on Windows 🧪

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-windows:
    runs-on:
      labels: windows-latest-8-cores

    steps:
      - name: Checkout testing directory 🔖
        uses: actions/checkout@v3
        with:
          repository: Satellite-im/Uplink

      - name: Set up cargo cache 🛠️
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install Rust 💿
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Setup cmake 🛠️
        uses: jwlawson/actions-setup-cmake@v1.13

      - name: Use cmake 💿
        run: cmake --version

      - name: Install Protoc 💿
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{env.GITHUB_TOKEN}}

      - name: Run cargo update 🌐
        run: cargo update

      - name: Run cargo clean 🧹
        run: cargo clean

      - name: Build resources 🖥️
        run: cargo build --release

      - name: Upload Artifact ⬆️
        uses: actions/upload-artifact@v3
        with:
          name: Uplink-Windows
          path: |
            target/release/ui.exe

  test-on-windows:
    needs: build-windows
    runs-on:
      labels: windows-latest-8-cores

    steps:
      - name: Checkout testing directory 🔖
        uses: actions/checkout@v3

      - name: Enable Developer Mode
        run: Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
        shell: powershell

      - name: Download the app 🗳️
        uses: actions/download-artifact@v1
        with:
          name: Uplink-Windows
          path: apps

      - name: Install NPM dependencies 📦
        run: npm install

      - name: Install and Run Appium Server 💻
        run: |
          npm install -g appium@next
          appium -v
          appium driver install --source=npm appium-windows-driver
          appium driver list

      - name: Run WebdriverIO tests on MacOS 🧪
        run: npm run windows.ci

      - name: Upload Screenshots if tests failed 📷
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: appium-screenshots
          path: ./test-results

      - name: Upload Appium Log if tests failed 📷
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: appium-log
          path: ./appium.log

      - name: Take screenshot of GH runner if test execution fails 📷
        uses: OrbitalOwen/desktop-screenshot-action@0.1
        if: failure()
        with:
          file-name: "desktop.jpg"
